drupalData:
    image: boran/drupal
    volumes:
    - /media/docker-data/biotika/drupal:/var/www/
    command: true

drupal:
    image: boran/drupal
    ports:
    - 8005:80
#    volumes:
#    - /media/docker-data/drupal6:/drupal6
    volumes_from:
    - drupalData
    environment:
      DRUPAL_MAKE_DIR: drupal-make
      DRUPAL_MAKE_REPO: https://github.com/gasparakos/biotika.git
      DRUPAL_MAKE_BRANCH: master


